-- Run this in the Supabase SQL Editor if the scores table does not exist yet.
-- The backend (leaderboard.py) expects: student_name, task_id, score, prompt, submitted_at.

CREATE TABLE IF NOT EXISTS scores (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name text NOT NULL,
  task_id      text NOT NULL,
  score        int  NOT NULL,
  prompt       text,
  submitted_at timestamptz DEFAULT now() NOT NULL
);

-- Optional: index for the "list student prompts" query (filter by task, order by time)
CREATE INDEX IF NOT EXISTS idx_scores_prompts_list
  ON scores (submitted_at DESC)
  WHERE prompt IS NOT NULL AND trim(prompt) <> '';
