-- Run this in the Supabase SQL Editor if the scores table does not exist yet.
-- The backend (leaderboard.py) expects: student_name, task_id, score, prompt, submitted_at,
-- plus optional research columns extraction_score and pillars_score (each 0–100).

CREATE TABLE IF NOT EXISTS scores (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name      text NOT NULL,
  task_id           text NOT NULL,
  score             int  NOT NULL,
  prompt            text,
  submitted_at      timestamptz DEFAULT now() NOT NULL,
  extraction_score  int,
  pillars_score     int
);

-- For existing databases created before these columns existed:
ALTER TABLE scores ADD COLUMN IF NOT EXISTS extraction_score int;
ALTER TABLE scores ADD COLUMN IF NOT EXISTS pillars_score int;

-- Optional: index for the "list student prompts" query (filter by task, order by time)
CREATE INDEX IF NOT EXISTS idx_scores_prompts_list
  ON scores (submitted_at DESC)
  WHERE prompt IS NOT NULL AND trim(prompt) <> '';
